name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: ["5.0"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{matrix.node-version}}
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}
      - name: Install dependencies
        run: npm install
      - name: Build client app
        run: npm run build --prefix client
      - name: Test node application
        run: npm test
