name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js version 16.x.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "16.x.x"
      - name: Install dependencies
        run: npm install
      - name: Build client app
        run: npm run build --prefix client
